config/routes.rb
Rails.application.routes.draw do
  get 'about',  to: 'home#about'
  get 'bug',  to: 'home#bug'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<section class="section--center mdl-grid mdl-grid--no-spacing ">
	<div class="mdl-cell mdl-cell--2-col mdl-cell--2-col-tablet"></div>
	<div class="mdl-cell mdl-cell--9-col mdl-cell--9-col-tablet">
		<h4>关于(About)</h4>
		<div class="demo-card-wide mdl-card mdl-shadow--1dp">
		  <div class="mdl-card__title">
		    <h2 class="mdl-card__title-text">杜小豆认可</h2>
		  </div>
		  <div class="mdl-card__supporting-text typo-styles__demo">
		  	<h4>
		    不要怀疑！不要怀疑！不要怀疑！<br>
		    站点内容已经通过杜小豆裁定认可，可供所有人查阅。<br>
			谁要是怀疑本站内容的真伪，杜小豆将有权将你驱逐离本站点。<br></h4>
		  </div>
		</div>
		<h5>社会评价</h5>
		<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">

			<div class="mdl-card mdl-cell mdl-cell--12-col">
				<div class="mdl-card__supporting-text mdl-grid mdl-grid--no-spacing">
					
					<div class="section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-table">
						<div class="section__circle-container__circle mdl-color--primary"></div>
					</div>
					
					<div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
						<h5>"渣男!"</h5>
						<div class="mdl-typography--text-right">
						    - 前女友
							&nbsp;&nbsp;&nbsp;&nbsp;
							&nbsp;&nbsp;&nbsp;&nbsp;
						</div>
					</div>
					
					<div class="section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone">
						<div class="section__circle-container__circle mdl-color--primary"></div>
					</div>

					<div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
						<h5>"喜欢瞎操心... ..."</h5>
						<div class="mdl-typography--text-right">
						    - 喜欢的女孩子
						</div>
					</div>
					
					<div class="section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone">
						<div class="section__circle-container__circle mdl-color--accent section__circle--big"></div>
					</div>
					
					<div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
        				<h5>"你有没有装B,自己心里没B数吗!"</h5>
        				<div class="mdl-typography--text-right">
						    - 一个老实人
						    &nbsp;&nbsp;
						</div>
					</div>
				</div>
			</div>
		</section>

		<h5>媒体评价</h5>
		<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">

			<div class="mdl-card mdl-cell mdl-cell--12-col">
				<div class="mdl-card__supporting-text mdl-grid mdl-grid--no-spacing">
					
					<div class="section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-table">
						<div class="section__circle-container__circle mdl-color--primary"></div>
					</div>
					
					<div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
						<h5>"除了'新手指南',就没有其他粉丝再关注过他!"</h5>
						<div class="mdl-typography--text-right">
						- <a href="https://weibo.com/u/5500893060" target="_blank">新浪微博</a>&nbsp;&nbsp;&nbsp;</div>
					</div>
					
					<div class="section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone">
						<div class="section__circle-container__circle mdl-color--primary"></div>
					</div>

					<div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
						<h5>"听歌独自爽,深夜单身汪!"</h5>
						<div class="mdl-typography--text-right">
						 - <a href="https://music.163.com/#/user/home?id=40659831" target="_blank">网易云音乐</a>
						</div>
					</div>
					
					<div class="section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone">
						<div class="section__circle-container__circle mdl-color--accent section__circle--big"></div>
					</div>
					
					<div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
        				<h5>"装完B就走,帐号也不留!"</h5>
        				<div class="mdl-typography--text-right">
        				- <a href="https://zhuanlan.zhihu.com/DuXiaoDou" target="_blank">知乎专栏</a>&nbsp;&nbsp;&nbsp;
        				</div>
					</div>
				</div>
			</div>
		</section>

		<h5>组织评价</h5>
		<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">

			<div class="mdl-card mdl-cell mdl-cell--12-col">
				<div class="mdl-card__supporting-text mdl-grid mdl-grid--no-spacing">
					
					<div class="section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone">
						<div class="section__circle-container__circle mdl-color--accent section__circle--big"></div>
					</div>
					
					<div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
        				<h5>"穿越大业,功在当代,利在千秋!组织很看好你啊,杜九!"</h5>
        				<div class="mdl-typography--text-right">
        				- <a href="https://lgqm.huijiwiki.com/wiki/%E7%94%A8%E6%88%B7:BlueMoon" target="_blank">临高启明</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        				</div>
					</div>

					<div class="section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone">
						<div class="section__circle-container__circle mdl-color--primary"></div>
					</div>

					<div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
						<h5>"Ruby和杜小豆,都是程序员的好朋友!"</h5>
						<div class="mdl-typography--text-right">
						 - <a href="https://ruby-china.org/BadTudou" target="_blank">Ruby-China</a>
						</div>
					</div>

					<div class="section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-table">
						<div class="section__circle-container__circle mdl-color--primary"></div>
					</div>
					
					<div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
						<h5>"BadTudou has no activity yet for this period."</h5>
						<div class="mdl-typography--text-right">
						- <a href="https://github.com/badtudou" target="_blank">GitHub</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
					</div>
					
				</div>
			</div>
		</section>
	</div>
	<div class="mdl-cell mdl-cell--1-col mdl-cell--1-col-tablet"></div>
</section>

app/views/home/bug.html.erb
<section class="section--center mdl-grid mdl-grid--no-spacing ">
	<div class="mdl-cell mdl-cell--2-col mdl-cell--2-col-tablet"></div>
	<div class="mdl-cell mdl-cell--9-col mdl-cell--9-col-tablet">
		<h4>反馈(Bug Reporting)</h4>
		<blockquote>
			足够多的眼睛，就可让所有问题浮现。 ——Linus定律
		</blockquote>
		<span class="mdl-chip mdl-chip--contact">
	    		<span class="mdl-chip__contact mdl-color--red mdl-color-text--white"><i class="material-icons">email</i></span>
	    		<span class="mdl-chip__text"><a href="mailto:badtudou@gmail.com">badtudou@gmail.com</a></span>
		</span>
		<p>
			若您发现本站点的任何Bug，请通过上面的电子邮箱与我联系。特别感谢以下人员为本站安全做出的努力与贡献！
		</p>

		<!-- <ul class="demo-list-three mdl-list">
		  <li class="mdl-list__item mdl-list__item--three-line">
		    <span class="mdl-list__item-primary-content">
		      <i class="material-icons mdl-list__item-avatar">person</i>
		      <span>Bryan Cranston</span>
		      <span class="mdl-list__item-text-body">
		        Bryan Cranston played the role of Walter in Breaking Bad. He is also known
		        for playing Hal in Malcom in the Middle.
		      </span>
		    </span>
		    <span class="mdl-list__item-secondary-content mdl-color-text--pink ">
		      <i class="material-icons">star</i>
		    </span>
		  </li>
		  <li class="mdl-list__item mdl-list__item--three-line">
		    <span class="mdl-list__item-primary-content">
		      <i class="material-icons  mdl-list__item-avatar">person</i>
		      <span>Aaron Paul</span>
		      <span class="mdl-list__item-text-body">
		        Aaron Paul played the role of Jesse in Breaking Bad. He also featured in
		        the "Need For Speed" Movie.
		      </span>
		    </span>
		    <span class="mdl-list__item-secondary-content mdl-color-text--pink ">
		     <i class="material-icons">star</i>
		    </span>
		  </li>
		  <li class="mdl-list__item mdl-list__item--three-line">
		    <span class="mdl-list__item-primary-content">
		      <i class="material-icons  mdl-list__item-avatar">person</i>
		      <span>Bob Odenkirk</span>
		      <span class="mdl-list__item-text-body">
		        Bob Odinkrik played the role of Saul in Breaking Bad. Due to public fondness for the
		        character, Bob stars in his own show now, called "Better Call Saul".
		      </span>
		    </span>
		    <span class="mdl-list__item-secondary-content mdl-color-text--pink ">
		      <i class="material-icons">star</i>
		    </span>
		  </li>
		</ul> -->
	</div>
</section>

app/views/home/index.html.erb
<%= render "shared/nav" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>杜小豆(BadTudou)</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.bootcss.com/material-design-icons/3.0.1/iconfont/material-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.bootcss.com/material-design-lite/1.3.0/material.indigo-pink.min.css">
    <script defer src="https://cdn.bootcss.com/material-design-lite/1.3.0/material.min.js"></script>
  </head>

  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <%= render "shared/header" %>
      <main class="mdl-layout__content">

        <div class="page-content">
          <%= yield %>
        </div>
      <%= render "shared/footer" %>
      </main>
      
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="mdl-mini-footer">
	<div class="mdl-cell mdl-cell--12-col mdl-typography--text-center">

	<strong>渝ICP备16010823号-1 <span class="badge badge-dark "><a href="http://www.miit.gov.cn/" title="工信部备案查询">工信部</a></span></strong>
	<br>

	<strong>Copyright © 2018 BadTudou. All rights reserved.</strong>
	</div>

</footer>

app/views/shared/_header.html.erb
<header class="mdl-layout__header mdl-color--grey">
	<div class="mdl-layout--large-screen-only mdl-layout__header-row">
	</div>

	<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">

		<header class="section__play-btn mdl-cell mdl-cell--3-col-desktop mdl-cell--2-col-tablet mdl-cell--4-col-phone mdl-color--teal-100 mdl-color-text--white">
		</header>
		<div class="mdl-card mdl-cell mdl-cell--9-col-desktop mdl-cell--6-col-tablet mdl-cell--4-col-phone">
			<div class="mdl-card__supporting-text">
				<h4><a href="<%= root_path %>"> 杜小豆(BadTudou)</a></h4>
                如果每个人都是一颗小星球，逝去的亲友就是身边的暗物质。我愿能再见你，我知我再见不到你。但你的引力仍在。我感激我们的光锥曾彼此重叠，而你永远改变了我的星轨。
                <br><br>
                纵使再不能相见，你仍是我所在的星系未曾分崩离析的原因，是我宇宙之网的永恒组成。 -- <科学松鼠会>
			</div>
		</div>
	</section>
	<div class="mdl-layout__header-row">
		<div class="mdl-cell mdl-cell--1-col mdl-cell--1-col-tablet">
		</div>
		<div class="mdl-cell mdl-cell--10-col mdl-cell--10-col-tablet">
			<%= render "shared/nav" %>
		</div>
		<div class="mdl-cell mdl-cell--1-col mdl-cell--1-col-tablet">
			
				<a href="<%= about_path %>">
					<label class="mdl-button mdl-js-button mdl-button--icon" for="fixed-header-drawer-exp">
						<i class="material-icons">help</i>
					</label>
				</a>
			
				<a href="<%= bug_path %>">
					<label class="mdl-button mdl-js-button mdl-button--icon" for="fixed-header-drawer-exp">
						<i class="material-icons">bug_report</i>
					</label>
				</a>
		</div>
	</div>

</header>

app/views/shared/_nav.html.erb
<div class="mdl-tabs  mdl-js-tabs mdl-js-ripple-effect ">
  <div class="mdl-tabs__tab-bar ">
      <a href="#starks-panel" class="mdl-color-text--pink mdl-tabs__tab is-active">Starks</a>
      <a href="#lannisters-panel" class="mdl-tabs__tab">Lannisters</a>
      <a href="#targaryens-panel" class="mdl-tabs__tab">Targaryens</a>
  </div>
</div>